
version: '3'
services:
  nagios:
    image: jasonrivers/nagios:4.4.6
    ports:
      - "8080:80"
    volumes:
      - nagios_data:/opt/nagios/etc
      - nagios_custom_plugins:/opt/Custom-Nagios-Plugins
      - nagiosgraph_var:/opt/nagiosgraph/var
      - nagiosgraph_etc:/opt/nagiosgraph/etc
    restart: always
  
  wireguard:
        image: lscr.io/linuxserver/wireguard:latest
        container_name: wireguard 
        cap_add:
        - NET_ADMIN
        - SYS_MODULE
        environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/London
        - SERVERURL=wireguard.domain.com #optional
        - SERVERPORT=51820 #optional
        - PEERS=1 #optional
        - PEERDNS=auto #optional
        - INTERNAL_SUBNET=10.13.13.0 #optional
        - ALLOWEDIPS=0.0.0.0/0 #optional
        - LOG_CONFS=true #optional
        volumes:
        - /path/to/appdata/config:/config
        
volumes:
  nagios_data:
  nagios_custom_plugins:
  nagiosgraph_var:
  nagiosgraph_etc: